[versions]
# Decompilers
cfr = "0.2.2"
vineflower = "1.11.1"

# Runtime depedencies
mixin-compile-extensions = "0.6.0"
dev-launch-injector = "0.2.1+build.8"
fabric-log4j-util = "1.0.2"
jetbrains-annotations = "26.0.2"
native-support = "1.0.1"
fabric-installer = "1.0.3"

# Dev tools
renderdoc = "1.37"
enigma = "3.0.1"

[libraries]
# Decompilers
cfr = { module = "net.fabricmc:cfr", version.ref = "cfr" }
vineflower = { module = "org.vineflower:vineflower", version.ref = "vineflower" }

# Runtime depedencies
mixin-compile-extensions = { module = "net.fabricmc:fabric-mixin-compile-extensions", version.ref = "mixin-compile-extensions" }
dev-launch-injector = { module = "net.fabricmc:dev-launch-injector", version.ref = "dev-launch-injector" }
fabric-log4j-util = { module = "net.fabricmc:fabric-log4j-util", version.ref = "fabric-log4j-util" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
native-support = { module = "net.fabricmc:fabric-loom-native-support", version.ref = "native-support" }
fabric-installer = { module = "net.fabricmc:fabric-installer", version.ref = "fabric-installer" }

# Dev tools
renderdoc = { module = "org.renderdoc:renderdoc", version.ref = "renderdoc" } # Not a maven dependency
enigma-swing = { module = "cuchaz:enigma-swing", version.ref = "enigma" }
